/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelDominio.Categoria;
import modelDominio.Cidade;
import modelDominio.Empresa;
import modelDominio.Estado;
import modelDominio.Usuario;
import view.util.ComboboxCategoria;
import view.util.ComboboxCidade;
import view.util.ComboboxEstado;
import view.util.Imagem;

/**
 *
 * @author be_ha
 */
public class FormPerfil extends javax.swing.JDialog {

    private Imagem imagem = null;
    
    /**
     * Creates new form FormPerfil
     */
    public FormPerfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Empresa empresa = AlfredCliente.ccont.empresa;
        initComponents();
        
        jTxtNome.setText(empresa.getNomeEmpresa());
        jTxtEmail.setText(empresa.getEmailUsuario());
        jTxtCnpj.setText(empresa.getCnpjEmpresa());
        preencheComboboxCategoria();
        preencheComboboxEstado();
        preencheComboboxCidade(empresa.getEstadoUsuario());
        
        jTxtBairro.setText(empresa.getBairroUsuario());
        jTxtRua.setText(empresa.getRuaUsuario());
        jTxtNumero.setText(empresa.getNumeroUsuarioToString());
        jTxtComplemento.setText(empresa.getComplementoUsuario());
        
        atualizarImagem(null);
//        if (empresa.getImagemEmpresa() != null) {
//            imagem = new Imagem(empresa.getImagemEmpresa());
////            jLbImagem.setIcon(imagem.getImageIcon());
//        }
    }
    
    // Testar
    private void atualizarImagem(File imagemCarregada) {
        Imagem imagem = null;
        if (imagemCarregada != null) {
            imagem = new Imagem(imagemCarregada);
            this.imagem = imagem;
        }else if (AlfredCliente.ccont.empresa.getImagemEmpresa() != null) {
            imagem = new Imagem(AlfredCliente.ccont.empresa.getImagemEmpresa());
            this.imagem = imagem;
        } else {
            imagem = new Imagem(new File(new File("").getAbsolutePath() + "\\src\\view\\imagens\\logo_PB.jpg"));
        }
        jLbImagem.setIcon(imagem.getImageIconRounded());
    }
    
    private void preencheComboboxCategoria() {
        ArrayList<Categoria> listaCategorias = new ArrayList<>();
        listaCategorias = AlfredCliente.ccont.categoriaLista();
        int selectedCategoria = -1;
        
        if (AlfredCliente.ccont.empresa.getCategoriaEmpresa() != null) {
            selectedCategoria = AlfredCliente.ccont.empresa.getCategoriaEmpresa().getCodCategoria() + 1;
        }
        
        ComboboxCategoria.preencheComboBoxCategoria(selectedCategoria, jCmbCategoria, listaCategorias, true);
    }
    
    private void preencheComboboxCidade(Estado est) {
        if (est != null) {            
            ArrayList<Cidade> listaCidades = new ArrayList<>();
            System.out.println("Estado" + est.getCodEstado() + ", " + est.getNomeEstado());
            listaCidades = AlfredCliente.ccont.getListaCidadesEstado(est);
            int cidadeSelecionada = -1;
            
            if (AlfredCliente.ccont.empresa.getCidadeUsuario()!= null) {
                cidadeSelecionada = AlfredCliente.ccont.empresa.getCidadeUsuario().getCodCidade() + 1;
            }

            ComboboxCidade.preencheComboBoxCidade(cidadeSelecionada , jCmbCidade, listaCidades, true);
        }
    }
    
    private void preencheComboboxEstado() {
        ArrayList<Estado> listaEstados = new ArrayList<>();
        listaEstados = AlfredCliente.ccont.getListaEstados();
        int estadoSelecionado = -1;
        
        if (AlfredCliente.ccont.empresa.getEstadoUsuario()!= null) {
            estadoSelecionado = AlfredCliente.ccont.empresa.getEstadoUsuario().getCodEstado()+ 1;
        }
        
        ComboboxEstado.preencheComboBoxEstado(estadoSelecionado, jCmbEstado, listaEstados, true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLbImagem = new javax.swing.JLabel();
        jBtnImagem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtCnpj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCmbCategoria = new javax.swing.JComboBox<>();
        jTxtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtRua = new javax.swing.JTextField();
        jTxtNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtComplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jCmbCidade = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTxtBairro = new javax.swing.JTextField();
        jCmbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        jLabel1.setText("Endereço do restaurante");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jBtnImagem.setBackground(new java.awt.Color(150, 150, 150));
        jBtnImagem.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jBtnImagem.setForeground(new java.awt.Color(255, 255, 255));
        jBtnImagem.setText("Alterar Imagem");
        jBtnImagem.setBorder(null);
        jBtnImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jBtnImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBtnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 150, 150));
        jLabel3.setText("Nome do Restaurante");

        jTxtNome.setBackground(new java.awt.Color(234, 234, 234));
        jTxtNome.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(150, 150, 150));
        jLabel4.setText("CNPJ");

        jTxtCnpj.setBackground(new java.awt.Color(234, 234, 234));
        jTxtCnpj.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(150, 150, 150));
        jLabel5.setText("Categoria");

        jCmbCategoria.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jCmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmbCategoria.setSelectedIndex(-1);

        jTxtEmail.setBackground(new java.awt.Color(234, 234, 234));
        jTxtEmail.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(150, 150, 150));
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        jLabel7.setText("Informações da empresa");

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(150, 150, 150));
        jLabel8.setText("Estado");

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(150, 150, 150));
        jLabel9.setText("Cidade");

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(150, 150, 150));
        jLabel10.setText("Rua");

        jTxtRua.setBackground(new java.awt.Color(234, 234, 234));
        jTxtRua.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N

        jTxtNumero.setBackground(new java.awt.Color(234, 234, 234));
        jTxtNumero.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(150, 150, 150));
        jLabel11.setText("Número");

        jTxtComplemento.setBackground(new java.awt.Color(234, 234, 234));
        jTxtComplemento.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(150, 150, 150));
        jLabel12.setText("Complemento");

        jBtnCancelar.setBackground(new java.awt.Color(150, 150, 150));
        jBtnCancelar.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setBorder(null);
        jBtnCancelar.setBorderPainted(false);
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnSalvar.setBackground(new java.awt.Color(150, 150, 150));
        jBtnSalvar.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jBtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setBorder(null);
        jBtnSalvar.setBorderPainted(false);
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jCmbCidade.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jCmbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmbCidade.setSelectedIndex(-1);
        jCmbCidade.setToolTipText("");
        jCmbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCidadeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(150, 150, 150));
        jLabel13.setText("Bairro");

        jTxtBairro.setBackground(new java.awt.Color(234, 234, 234));
        jTxtBairro.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N

        jCmbEstado.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jCmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmbEstado.setSelectedIndex(-1);
        jCmbEstado.setToolTipText("");
        jCmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(558, 558, 558)
                        .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jTxtNome)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(227, 227, 227)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jCmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel6)
                                .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(308, 308, 308)
                            .addComponent(jLabel9)
                            .addGap(258, 258, 258)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(jCmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTxtComplemento))))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jCmbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCidadeActionPerformed
        
    }//GEN-LAST:event_jCmbCidadeActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        String nomeEmpresa = jTxtNome.getText();
        String cnpjEmpresa = jTxtCnpj.getText();
        String emailEmpresa = jTxtEmail.getText();
        String bairroEmpresa = jTxtBairro.getText();
        String ruaEmpresa = jTxtRua.getText();
        String numeroEmpresa = jTxtNumero.getText();
        
        if (nomeEmpresa.equals("")) {
            JOptionPane.showMessageDialog(this, "Insira o Nome do restaurante", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else if (cnpjEmpresa.equals("") || !Empresa.validaCnpj(cnpjEmpresa)) {
            JOptionPane.showMessageDialog(this, "Insera um Cnpj válido", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else if (emailEmpresa.equals("") || !Usuario.validaEmail(emailEmpresa)) {
            JOptionPane.showMessageDialog(this, "Insera um Email válido", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else if (bairroEmpresa.equals("")) {
            JOptionPane.showMessageDialog(this, "Insera o Bairro", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else if (ruaEmpresa.equals("")) {
            JOptionPane.showMessageDialog(this, "Insera a Rua", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else if (numeroEmpresa.equals("")) {
            JOptionPane.showMessageDialog(this, "Insera o Número do endereço", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else  if (jCmbCategoria.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma Categoria", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else  if (jCmbEstado.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado ", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else  if (jCmbCidade.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma Cidade ", this.getTitle(), JOptionPane.ERROR_MESSAGE);
        } else {
            byte[] imagemSelecionada = AlfredCliente.ccont.empresa.getImagemEmpresa();
            if (imagem != null){
                imagemSelecionada = imagem.getImagem();
            }
            
            Categoria catSelecionada = new Categoria(jCmbCategoria.getSelectedIndex(), jCmbCategoria.getSelectedItem().toString());
            Empresa emp = new Empresa(
                AlfredCliente.ccont.empresa.getCodEmpresa(),
                jTxtNome.getText(), 
                jTxtCnpj.getText(), 
                AlfredCliente.ccont.empresa.getAbertoFechadoEmpresa(), 
                catSelecionada,
                imagemSelecionada
            );
            
            Cidade cid = new Cidade(jCmbCidade.getSelectedItem().toString(), jCmbEstado.getSelectedIndex());
            Cidade cidadeSelecionada = AlfredCliente.ccont.buscarCidade(cid);
            Estado est = new Estado(jCmbEstado.getSelectedIndex());
            
            Usuario usr = new Usuario(
                AlfredCliente.ccont.empresa.getCodUsuario(), 
                emailEmpresa,
                AlfredCliente.ccont.empresa.getSenhaUsuario(),
                cidadeSelecionada, 
                est, 
                ruaEmpresa, 
                bairroEmpresa, 
                jTxtComplemento.getText(), 
                Integer.parseInt(numeroEmpresa)
            );
            
            String okEmpresa = AlfredCliente.ccont.empresaAlterar(emp);
            String okUsuario = AlfredCliente.ccont.usuarioAlterar(usr);
            
            if (okEmpresa.equals("ok")) {
                AlfredCliente.ccont.empresa.setNomeEmpresa(emp.getNomeEmpresa());
                AlfredCliente.ccont.empresa.setCnpjEmpresa(emp.getCnpjEmpresa());
                AlfredCliente.ccont.empresa.setCategoriaEmpresa(emp.getCategoriaEmpresa());
                AlfredCliente.ccont.empresa.setImagemEmpresa(emp.getImagemEmpresa());
            }
            
            if (okUsuario.equals("ok")) {
                AlfredCliente.ccont.empresa.setEmailUsuario(usr.getEmailUsuario());
                AlfredCliente.ccont.empresa.setCidadeUsuario(cidadeSelecionada);
                AlfredCliente.ccont.empresa.setEstadoUsuario(est);
                AlfredCliente.ccont.empresa.setRuaUsuario(usr.getRuaUsuario());
                AlfredCliente.ccont.empresa.setBairroUsuario(usr.getBairroUsuario());
                AlfredCliente.ccont.empresa.setComplementoUsuario(usr.getComplementoUsuario());
                AlfredCliente.ccont.empresa.setNumeroUsuario(usr.getNumeroUsuario());
            } 
            
            if(okEmpresa.equals("ok") && okUsuario.equals("ok")) {
                dispose();
                JOptionPane.showMessageDialog(this, "Perfil atualizado com sucesso", this.getTitle(), JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar perfil", this.getTitle(), JOptionPane.ERROR_MESSAGE);                
            }
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jCmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbEstadoActionPerformed
        int codEstado = jCmbEstado.getSelectedIndex();
        if (codEstado > 0) {
            Estado est = new Estado(codEstado);
            preencheComboboxCidade(est);
        }
    }//GEN-LAST:event_jCmbEstadoActionPerformed

    private void jBtnImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImagemActionPerformed
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        jFileChooser1.addChoosableFileFilter(imageFilter);
        if (jFileChooser1.showOpenDialog(this) ==  JFileChooser.APPROVE_OPTION){
//            imagem = new Imagem(jFileChooser1.getSelectedFile());
//            jLbImagem.setIcon(imagem.getImageIcon());
            this.atualizarImagem(jFileChooser1.getSelectedFile());
        }
    }//GEN-LAST:event_jBtnImagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPerfil dialog = new FormPerfil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnImagem;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox<String> jCmbCategoria;
    private javax.swing.JComboBox<String> jCmbCidade;
    private javax.swing.JComboBox<String> jCmbEstado;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbImagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCnpj;
    private javax.swing.JTextField jTxtComplemento;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNumero;
    private javax.swing.JTextField jTxtRua;
    // End of variables declaration//GEN-END:variables
}
